USE [master]
GO

/****** Object:  Database [TheHrmDB]    Script Date: 2018/05/30 17:09:44 ******/
CREATE DATABASE [TheHrmDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TheHrmDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\TheHrmDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TheHrmDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\TheHrmDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TheHrmDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TheHrmDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TheHrmDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TheHrmDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TheHrmDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TheHrmDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TheHrmDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TheHrmDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TheHrmDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TheHrmDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TheHrmDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TheHrmDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TheHrmDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TheHrmDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TheHrmDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TheHrmDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TheHrmDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TheHrmDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TheHrmDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TheHrmDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TheHrmDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TheHrmDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TheHrmDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TheHrmDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TheHrmDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TheHrmDB] SET  MULTI_USER 
GO

ALTER DATABASE [TheHrmDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TheHrmDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TheHrmDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TheHrmDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TheHrmDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TheHrmDB] SET QUERY_STORE = OFF
GO

USE [TheHrmDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TheHrmDB] SET  READ_WRITE 
GO

